#!/bin/bash
set -e

# Elite Adventures Belize - Deployment Script
# This script deploys the entire application infrastructure and code

echo "🚀 Starting deployment..."

# Load environment variables
if [ -f .env ]; then
  export $(cat .env | grep -v '^#' | xargs)
else
  echo "⚠️  .env file not found. Using defaults from .env.sample"
fi

# Set defaults
AWS_REGION=${AWS_REGION:-us-east-1}
PROJECT_NAME=${PROJECT_NAME:-elite-adventures-leads}
ENVIRONMENT=${ENVIRONMENT:-prod}

echo "📋 Configuration:"
echo "  Region: $AWS_REGION"
echo "  Project: $PROJECT_NAME"
echo "  Environment: $ENVIRONMENT"
echo ""

# Step 1: Install Lambda dependencies
echo "📦 Installing Lambda dependencies..."
for lambda_dir in lambdas/leads lambdas/exports lambdas/conference; do
  if [ -f "$lambda_dir/package.json" ]; then
    echo "  → $lambda_dir"
    (cd $lambda_dir && npm install --production --silent)
  fi
done
echo "✓ Lambda dependencies installed"
echo ""

# Step 2: Build frontend application
echo "🔨 Building frontend application..."
(cd app && npm run build)
echo "✓ Frontend built"
echo ""

# Step 3: Terraform - Infrastructure deployment
echo "🏗️  Deploying infrastructure with Terraform..."
cd infra/terraform

# Initialize Terraform
echo "  → Initializing Terraform..."
terraform init -upgrade

# Plan
echo "  → Planning infrastructure changes..."
terraform plan -out=tfplan \
  -var="project_name=$PROJECT_NAME" \
  -var="environment=$ENVIRONMENT" \
  -var="aws_region=$AWS_REGION"

# Apply
echo "  → Applying infrastructure changes..."
echo "    (This may take 5-10 minutes...)"
terraform apply tfplan

# Get outputs
echo "  → Retrieving infrastructure outputs..."
SITE_BUCKET=$(terraform output -raw site_bucket_name)
API_URL=$(terraform output -raw api_url)
COGNITO_POOL_ID=$(terraform output -raw cognito_user_pool_id)
COGNITO_CLIENT_ID=$(terraform output -raw cognito_client_id)
COGNITO_DOMAIN=$(terraform output -raw cognito_domain)

cd ../..

echo "✓ Infrastructure deployed"
echo ""

# Step 4: Inject configuration into frontend
echo "⚙️  Injecting configuration into frontend..."
cat > app/public/config.js << EOF
window.CONFIG = {
  API_URL: '$API_URL',
  COGNITO_POOL_ID: '$COGNITO_POOL_ID',
  COGNITO_CLIENT_ID: '$COGNITO_CLIENT_ID',
  COGNITO_DOMAIN: '$COGNITO_DOMAIN',
  AWS_REGION: '$AWS_REGION'
};
EOF

# Update index.html to include config
if ! grep -q "config.js" app/public/index.html; then
  sed -i.bak 's|<script src="/bundle.js"></script>|<script src="/config.js"></script>\n  <script src="/bundle.js"></script>|' app/public/index.html
  rm app/public/index.html.bak
fi

echo "✓ Configuration injected"
echo ""

# Step 5: Deploy frontend to S3
echo "📤 Deploying frontend to S3..."
aws s3 sync app/public/ "s3://$SITE_BUCKET/" \
  --delete \
  --region $AWS_REGION \
  --cache-control "public, max-age=3600" \
  --exclude "*.map"

# Set special cache headers for HTML (no cache)
aws s3 cp app/public/index.html "s3://$SITE_BUCKET/index.html" \
  --cache-control "no-cache, no-store, must-revalidate" \
  --region $AWS_REGION

echo "✓ Frontend deployed"
echo ""

# Step 6: Display deployment info
echo "✅ Deployment complete!"
echo ""
echo "=========================================="
echo "📊 Deployment Information"
echo "=========================================="
echo ""
echo "🌐 Website URL:"
echo "   http://$SITE_BUCKET.s3-website-$AWS_REGION.amazonaws.com"
echo ""
echo "🔗 API URL:"
echo "   $API_URL"
echo ""
echo "🔐 Cognito Configuration:"
echo "   Pool ID:   $COGNITO_POOL_ID"
echo "   Client ID: $COGNITO_CLIENT_ID"
echo "   Domain:    $COGNITO_DOMAIN"
echo ""
echo "=========================================="
echo ""

# Save configuration to .env file
echo "💾 Updating .env file with deployment outputs..."
cat > .env << EOF
# AWS Configuration
AWS_REGION=$AWS_REGION
AWS_PROFILE=${AWS_PROFILE:-default}

# Project Configuration
PROJECT_NAME=$PROJECT_NAME
ENVIRONMENT=$ENVIRONMENT

# Deployed Infrastructure (generated by Terraform)
SITE_BUCKET_NAME=$SITE_BUCKET
API_GATEWAY_URL=$API_URL
COGNITO_USER_POOL_ID=$COGNITO_POOL_ID
COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
COGNITO_DOMAIN=$COGNITO_DOMAIN
EOF

echo "✓ .env file updated"
echo ""

# Get admin password if created
ADMIN_TEMP_PASSWORD=$(cd infra/terraform && terraform output -raw admin_temp_password 2>/dev/null || echo "")
if [ ! -z "$ADMIN_TEMP_PASSWORD" ] && [ "$ADMIN_TEMP_PASSWORD" != "N/A - No admin user created" ]; then
  echo "⚠️  IMPORTANT: Admin user created!"
  echo "   Temporary password: $ADMIN_TEMP_PASSWORD"
  echo "   Please change this password on first login."
  echo ""
fi

echo "📚 Next Steps:"
echo "   1. Visit the website URL above to test the public form"
echo "   2. Run './scripts/seed.sh' to create sample conference and test data"
echo "   3. Access admin interface at: [SITE_URL]#admin"
if [ ! -z "$ADMIN_TEMP_PASSWORD" ] && [ "$ADMIN_TEMP_PASSWORD" != "N/A - No admin user created" ]; then
  echo "   4. Login with your admin credentials (password above)"
else
  echo "   4. Create admin users in Cognito console"
fi
echo ""
echo "🎉 Happy lead capturing!"
