#!/bin/bash

# Elite Adventures Belize - API Testing Script
# Provides example cURL commands for all API endpoints

# Load environment
if [ -f .env ]; then
  export $(cat .env | grep -v '^#' | xargs)
fi

API_URL=${API_GATEWAY_URL:-"https://api.example.com"}
CONFERENCE_ID=${1:-"test-conference"}

echo "🧪 API Testing Commands"
echo "======================="
echo ""
echo "API URL: $API_URL"
echo "Conference ID: $CONFERENCE_ID"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}PUBLIC ENDPOINTS (No Auth Required)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

echo -e "${GREEN}1. POST /leads${NC} - Submit a new lead"
echo "----------------------------------------"
echo "curl -X POST '$API_URL/leads' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"conferenceId\": \"$CONFERENCE_ID\","
echo "    \"firstName\": \"John\","
echo "    \"lastName\": \"Doe\","
echo "    \"email\": \"john.doe@example.com\","
echo "    \"phone\": \"+15551234567\","
echo "    \"company\": \"Example Corp\","
echo "    \"role\": \"CEO\","
echo "    \"businessType\": \"travel-agency\","
echo "    \"interests\": [\"diving\", \"luxury\"],"
echo "    \"tripWindow\": \"3-6-months\","
echo "    \"groupSize\": 20,"
echo "    \"notes\": \"Interested in group packages\","
echo "    \"consentContact\": true,"
echo "    \"consentMarketing\": true"
echo "  }'"
echo ""

echo -e "${GREEN}2. GET /conference/{id}${NC} - Get conference configuration"
echo "----------------------------------------"
echo "curl -X GET '$API_URL/conference/$CONFERENCE_ID'"
echo ""

echo -e "${GREEN}3. GET /qr/{id}${NC} - Get QR code for conference"
echo "----------------------------------------"
echo "curl -X GET '$API_URL/qr/$CONFERENCE_ID?format=png&size=300' \\"
echo "  -o qr-code.png"
echo ""
echo "# Or get SVG format:"
echo "curl -X GET '$API_URL/qr/$CONFERENCE_ID?format=svg' \\"
echo "  -o qr-code.svg"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}ADMIN ENDPOINTS (Auth Required)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}Note: Replace YOUR_JWT_TOKEN with your Cognito ID token${NC}"
echo ""

echo -e "${GREEN}4. GET /leads${NC} - List all leads (with pagination)"
echo "----------------------------------------"
echo "curl -X GET '$API_URL/leads' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"
echo ""
echo "# Filter by conference:"
echo "curl -X GET '$API_URL/leads?conferenceId=$CONFERENCE_ID' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"
echo ""
echo "# With pagination:"
echo "curl -X GET '$API_URL/leads?limit=50&lastKey=BASE64_ENCODED_KEY' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"
echo ""

echo -e "${GREEN}5. GET /leads/{id}${NC} - Get specific lead"
echo "----------------------------------------"
echo "curl -X GET '$API_URL/leads/01ARZ3NDEKTSV4RRFFQ69G5FAV?conferenceId=$CONFERENCE_ID' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN'"
echo ""

echo -e "${GREEN}6. PATCH /leads/{id}${NC} - Update lead status/notes"
echo "----------------------------------------"
echo "curl -X PATCH '$API_URL/leads/01ARZ3NDEKTSV4RRFFQ69G5FAV?conferenceId=$CONFERENCE_ID' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"Status\": \"contacted\","
echo "    \"Tags\": [\"hot-lead\", \"priority\"],"
echo "    \"AdminNotes\": \"Followed up via phone. Very interested.\""
echo "  }'"
echo ""

echo -e "${GREEN}7. POST /export${NC} - Export leads to CSV/JSON"
echo "----------------------------------------"
echo "# Export all leads as CSV:"
echo "curl -X POST '$API_URL/export' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"format\": \"csv\""
echo "  }'"
echo ""
echo "# Export filtered leads as JSON:"
echo "curl -X POST '$API_URL/export' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"format\": \"json\","
echo "    \"filters\": {"
echo "      \"conferenceId\": \"$CONFERENCE_ID\","
echo "      \"status\": \"new\","
echo "      \"dateFrom\": \"2024-01-01T00:00:00Z\""
echo "    }"
echo "  }'"
echo ""

echo -e "${GREEN}8. POST /conference${NC} - Create/update conference"
echo "----------------------------------------"
echo "curl -X POST '$API_URL/conference' \\"
echo "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"conferenceId\": \"$CONFERENCE_ID\","
echo "    \"name\": \"Travel Trade Show 2024\","
echo "    \"enabled\": true,"
echo "    \"customFields\": {"
echo "      \"venue\": \"Convention Center\","
echo "      \"date\": \"2024-06-15\""
echo "    }"
echo "  }'"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}GETTING AN AUTH TOKEN${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "To get a JWT token for testing admin endpoints:"
echo ""
echo "1. Via Cognito Hosted UI:"
echo "   - Visit: $COGNITO_DOMAIN/login"
echo "   - Login with your credentials"
echo "   - Extract the id_token from the redirect URL"
echo ""
echo "2. Via AWS CLI (if you have admin credentials):"
echo "   aws cognito-idp admin-initiate-auth \\"
echo "     --user-pool-id $COGNITO_USER_POOL_ID \\"
echo "     --client-id $COGNITO_CLIENT_ID \\"
echo "     --auth-flow ADMIN_NO_SRP_AUTH \\"
echo "     --auth-parameters USERNAME=your-email@example.com,PASSWORD=your-password"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}COMMON STATUS CODES${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "200 - Success (GET, PATCH)"
echo "201 - Created (POST /leads)"
echo "400 - Bad Request (validation error)"
echo "401 - Unauthorized (missing/invalid auth token)"
echo "403 - Forbidden (insufficient permissions)"
echo "404 - Not Found"
echo "429 - Too Many Requests (rate limited by WAF)"
echo "500 - Internal Server Error"
echo ""
